id: 
  auxiliar: true

title:
  auxiliar: true

condition:
  descritiva: true

thumbnail_id:
  auxiliar: true

catalog_product_id:
  auxiliar: true

listing_type_id:
  descritiva: true

sanitized_title:
  hard_remove: true

permalink:
  auxiliar: true

buying_mode:
  descritiva: true

site_id:
  descritiva: true

category_id:
  auxiliar: true
  cria_feature: true

domain_id:
  auxiliar: true
  cria_feature: true

thumbnail:
  auxiliar: true

currency_id:
  descritiva: true

order_backend:
  hard_remove: true

price:
  descritiva: true

original_price:
  descritiva: true

sale_price:
  struct: true

available_quantity:
  descritiva: true
  fill_null: true

official_store_id:
  auxiliar: true

official_store_name:
  auxiliar: true

use_thumbnail_id:
  descritiva: true
  bool: True

accepts_mercadopago:
  descritiva: true
  bool: true

shipping:
  struct: true

stop_time:
  auxiliar: true

seller:
  struct: true

address:
  struct: true

attributes:
  struct: true

location:
  struct: true

seller_contact:
  struct: true

installments:
  struct: true

winner_item_id:
  hard_remove: true

catalog_listing:
  descritiva: true
  bool: True

discounts:
  hard_remove: true

promotion_decorations:
  hard_remove: true

promotions:
  hard_remove: true

inventory_id:
  hard_remove: true

# sale_price_conditions_start_time:
#   auxiliar: true
#   cria_feature: true

# sale_price_conditions_end_time:
#   auxiliar: true
#   cria_feature: true

sale_price_conditions_eligible:
  descritiva: true
  bool: true

sale_price_metadata_promotion_type:
  descritiva: true

sale_price_payment_method_type:
  descritiva: true

sale_price_type:
  hard_remove: true

price_tratado:
  descritiva: true

attributes_brand_value:
  descritiva: true
  feature_to_group: 100

attributes_color_value:
  descritiva: true

attributes_main_color_value:
  descritiva: true

attributes_weight_value:
  descritiva: true

shipping_free_shipping:
  descritiva: true
  bool: True

shipping_logistic_type:
  descritiva: true

address_city_name:
  descritiva: true
  feature_to_group: 100

address_state_name:
  descritiva: true
  feature_to_group: 100

installments_quantity:
  descritiva: true
  fill_null: true

# installments_metadata_additional_bank_interest:
#   descritiva: true
#   bool: true

# installments_metadata_meliplus_installments:
#   descritiva: true
#   bool: true


#####################################################################################
######################### FEATURES CRIADA NO CriaFeatures ###########################
#####################################################################################

domain_id_tratado:
  feature_to_group: 100
  feature_to_normalize: true

category_id_tratado:
  feature_to_group: 100

# sale_price_conditions_start_time_day: 
#   fill_null: true

# sale_price_conditions_start_time_month:
#   fill_null: true

# sale_price_conditions_start_time_weekday:
#   fill_null: true

# diff_start_end_time:
#   fill_null: true

# diff_start_stop_time:
#   fill_null: true

installments_price:
  fill_null: true


#####################################################################################
##################################### TARGETS #######################################
#####################################################################################

promotion_flag:
  target_clf: true

discount:
  target_reg: true